Zooming with keyboard
anegostudios/vsessentialsmod pull request #5
Opened 2024-01-12 07:54 UTC by Craluminum2413

Zoom+ with `Page Up` and `+`
Zoom- with `Page Down` and `-`

2024-01-12 16:33 UTC, Longboyy requested changes
Good change, just needs a few changes to add keybindings and simplification of the copy-pasted code.

2024-01-12 16:33 UTC, Longboyy commented on Systems/WorldMap/GuiElementMap.cs
> +            if (args.KeyCode == (int)GlKeys.PageUp || args.KeyCode == (int)GlKeys.Plus)
Hardcoded keys. Use `ICoreClientAPI.Input.RegisterHotKey`

2024-01-12 16:33 UTC, Longboyy commented on Systems/WorldMap/GuiElementMap.cs
> +                this.ZoomAdd(
Copy-pasted code can be simplified.

2024-01-22 11:03 UTC, tyronx commented
this indeed should not be hardcoded

2024-09-25 16:41 UTC, Craluminum2413 commented
Opened the same PR with fixed problems
https://github.com/anegostudios/vsessentialsmod/pull/10

2024-09-30 09:53 UTC, Craluminum2413 commented
Oh it is in 1.20 now, I haven't noticed

2024-09-30 09:53 UTC, closed without merging